### ISSUE TITLE
Symlinks are followed in matryoshka mode

### ISSUE THREAD

**Issue by sviehb** [devttys0/binwalk#118]
Here binwalk tried to follow a broken symlink:
```
Signature Exception: [Errno 2] No such file or directory: '[REMOVED]'
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/module.py", line 521, in main
    retval = self.run()
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/signature.py", line 175, in run
    for fp in iter(self.next_file, None):
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/module.py", line 366, in next_file
    fp = self.config.open_file(next_target_file)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/general.py", line 163, in open_file
    return binwalk.core.common.BlockFile(fname, subclass=self.subclass, length=length, offset=offset, swap=swap, block=block, peek=peek)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/common.py", line 480, in BlockFile
    return InternalBlockFile(fname, mode=mode, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/common.py", line 317, in __init__
    super(self.__class__, self).__init__(fname, mode)
IOError: [Errno 2] No such file or directory: '[REMOVED]'
----------------------------------------------------------------------------------------------------
```
I'd suggest not following symlinks at all because of security :turtle:

**Comment by devttys0** [comment]
Agreed! Just checked in a patch that prevents the extractor from following symlinks.
