### ISSUE TITLE
Binwalk barfs using magic.mgc from `file`

### ISSUE THREAD

**Issue by bus1ng** [devttys0/binwalk#143]
I have file 5.24 and binwalk v2.1.0 installed from git on x86_64 Arch Linux.

Given that the -m option says it accepts a magic file to use, I would expect the magic file from `file` (which provides libmagic.so) to work. But handing it to binwalk results in barf from trying to interpret the .mgc file as text?

```
$ file /usr/share/file/misc/magic.mgc    
/usr/share/file/misc/magic.mgc: magic binary file for file(1) cmd (version 13) (little endian)
```

```
$ binwalk -m /usr/share/file/misc/magic.mgc /dev/null
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/binwalk/core/module.py", line 509, in main
    self.init()
  File "/usr/lib/python3.4/site-packages/binwalk/modules/signature.py", line 98, in init
    self.magic.load(f)
  File "/usr/lib/python3.4/site-packages/binwalk/core/magic.py", line 793, in load
    lines = fp.readlines()
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 3: invalid continuation byte
----------------------------------------------------------------------------------------------------
```

**Comment by devttys0** [comment]
Binwalk signatures are based on, but not completely compatible with, signatures used by `libmagic`. See the wiki entry on signatures for more details: https://github.com/devttys0/binwalk/wiki/Creating-Custom-Signatures
