### ISSUE TITLE
Feature request: Support for Lancom images

### ISSUE THREAD

**Issue by hannob** [devttys0/binwalk#170]
I am currently unable to unpack Lancom images with binwalk. I have seen that at least some preliminary support has been committed in issue #66 and #67.

The images come with the extension .upx (but I think this is totally unrelated to the upx exe packer).

When I try to extract these images with the current binwalk git code I get an error:
Signature Exception: coercing to Unicode: need string or buffer, long found
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/binwalk/core/module.py", line 565, in main
    retval = self.run()
  File "/usr/lib/python2.7/site-packages/binwalk/modules/signature.py", line 177, in run
    self.scan_file(fp)
  File "/usr/lib/python2.7/site-packages/binwalk/modules/signature.py", line 160, in scan_file
    self.result(r=r)
  File "/usr/lib/python2.7/site-packages/binwalk/core/module.py", line 449, in result
    self.validate(r)
  File "/usr/lib/python2.7/site-packages/binwalk/modules/signature.py", line 112, in validate
    if r.size and (r.size + r.offset) > r.file.size:
TypeError: coercing to Unicode: need string or buffer, long found
----------------------------------------------------------------------------------------------------

(this is with this example file:
ftp://ftp.lancom.de/LANCOM-Archive/LC-9100-plus/LC-9100plus-8.82.0100-RU1.upx
)

The extraction produces a couple of files in this form:
2068     344A40     3CF388     3CF42C     44B9DC     44BFD4
2068.7z  344A40.7z  3CF388.7z  3CF42C.7z  44B9DC.7z  44BFD4.7z

But they don't seem to be useful files either, there is probably a second extraction step neccesary.

I hope it is okay that I'm posting this here (but I didn't see any kind of other contact or forum that would be appropriate).

**Comment by devttys0** [comment]
The exception is a side-effect of a recent pull request (#167). I've just checked in a patch that should fix it.

IIRC, LANCOM uses a custom RTOS for at least part of their firmware that uses "ZLoader" (there are strings referencing ZLoader in your firmware image). This would need to be reverse engineered, if it hasn't been already, to determine how the image needs to be extracted.
