### ISSUE TITLE
binwalk can use on windows?

### ISSUE THREAD

**Issue by TramyLee** [devttys0/binwalk#182]
I want to use binwalk.But my Os is windows8.1,I try to binwalk python.Erro is follow:

General Error: Cannot open file : [Errno 2] No such file or directory: 'firmware
2.bin'

General Error: Cannot open file : [Errno 2] No such file or directory: 'firmware
2.bin'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Python27\lib\site-packages\binwalk\__init__.py", line 8, in scan
    objs = m.execute()
  File "d:\Python27\lib\site-packages\binwalk\core\module.py", line 729, in exec
ute
    obj = self.run(module)
  File "d:\Python27\lib\site-packages\binwalk\core\module.py", line 746, in run
    obj = self.load(module, kwargs)
  File "d:\Python27\lib\site-packages\binwalk\core\module.py", line 774, in load

**Comment by devttys0** [comment]
That error indicates that the file `firmware2.bin` does not exist. Are you sure you specified the correct path and file name?
