### ISSUE TITLE
Cannot save entropy plot in the absense of X

### ISSUE THREAD

**Issue by fake-name** [devttys0/binwalk#280]
```
vagrant@vagrant:/code/Misc/Trimble/MSMobile5_503_1250_OperatingSystem_TSC2⟫ binwalk -E -J wat.txt

DECIMAL       HEXADECIMAL     ENTROPY
--------------------------------------------------------------------------------
0             0x0             Falling entropy edge (0.198120)
QXcbConnection: Could not connect to display
Aborted
```

`wat.txt` is a text file containing the three bytes `wat`. 

This is a VM without any UI components. I understand that displaying the file entropy is probably not reasonable, but there's no reason *saving* a file should fail. 

GDB StackDump (for a different file, but that shouldn't make a difference):

```
vagrant@vagrant:/code/Misc/Trimble/MSMobile5_503_1250_OperatingSystem_TSC2⟫ gdb --args python3 /usr/local/bin/binwalk -E -J FWV5_0_3WWE.img
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/python3 /usr/local/bin/binwalk -E -J FWV5_0_3WWE.img
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea651700 (LWP 30060)]
[New Thread 0x7fffe9e50700 (LWP 30061)]
[New Thread 0x7fffe564f700 (LWP 30062)]

DECIMAL       HEXADECIMAL     ENTROPY
--------------------------------------------------------------------------------
0             0x0             Falling entropy edge (0.756011)
172032        0x2A000         Falling entropy edge (0.605149)
540672        0x84000         Rising entropy edge (0.955983)
1294336       0x13C000        Rising entropy edge (0.974166)
2883584       0x2C0000        Falling entropy edge (0.842440)
2969600       0x2D5000        Rising entropy edge (0.996469)
24100864      0x16FC000       Falling entropy edge (0.625845)
QXcbConnection: Could not connect to display

Thread 1 "python3" received signal SIGABRT, Aborted.
0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff782702a in __GI_abort () at abort.c:89
#2  0x00007ffff3f96d9e in QMessageLogger::fatal(char const*, ...) const () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Core.so.5
#3  0x00007fffe0d8625e in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) ()
   from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#4  0x00007fffe0d8b505 in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) ()
   from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#5  0x00007fffe108d43d in ?? () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforms/libqxcb.so
#6  0x00007ffff473bbfb in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) ()
   from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#7  0x00007ffff4749436 in QGuiApplicationPrivate::createPlatformIntegration() () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#8  0x00007ffff4749edd in QGuiApplicationPrivate::createEventDispatcher() () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#9  0x00007ffff417d7d6 in QCoreApplicationPrivate::init() () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Core.so.5
#10 0x00007ffff474b6ab in QGuiApplicationPrivate::init() () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#11 0x00007fffee31ed09 in QApplicationPrivate::init() () from /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#12 0x00007fffeec41ce9 in sipQApplication::sipQApplication(int&, char**, int) () from /usr/local/lib/python3.5/dist-packages/PyQt5/QtWidgets.so
#13 0x00007fffeec41db9 in init_type_QApplication () from /usr/local/lib/python3.5/dist-packages/PyQt5/QtWidgets.so
#14 0x00007fffef5f861b in sipSimpleWrapper_init () from /usr/local/lib/python3.5/dist-packages/sip.so
#15 0x000000000055d17c in ?? ()
#16 0x00000000005b7167 in PyObject_Call ()
#17 0x0000000000528d06 in PyEval_EvalFrameEx ()
#18 0x0000000000528814 in PyEval_EvalFrameEx ()
#19 0x000000000052d2e3 in ?? ()
#20 0x0000000000529332 in PyEval_EvalFrameEx ()
#21 0x0000000000528814 in PyEval_EvalFrameEx ()
#22 0x0000000000528814 in PyEval_EvalFrameEx ()
#23 0x0000000000528814 in PyEval_EvalFrameEx ()
#24 0x0000000000528814 in PyEval_EvalFrameEx ()
#25 0x0000000000528814 in PyEval_EvalFrameEx ()
#26 0x000000000052d2e3 in ?? ()
#27 0x0000000000528eee in PyEval_EvalFrameEx ()
#28 0x000000000052d2e3 in ?? ()
#29 0x0000000000529332 in PyEval_EvalFrameEx ()
#30 0x0000000000528814 in PyEval_EvalFrameEx ()
#31 0x000000000052d2e3 in ?? ()
#32 0x000000000052dfdf in PyEval_EvalCode ()
#33 0x00000000005fd2c2 in ?? ()
#34 0x00000000005ff76a in PyRun_FileExFlags ()
#35 0x00000000005ff95c in PyRun_SimpleFileExFlags ()
#36 0x000000000063e7d6 in Py_Main ()
#37 0x00000000004cfe41 in main ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 30056] will be killed.

Quit anyway? (y or n) y
```

**Comment by devttys0** [comment]
This is a known issue, addressed in the [FAQ](https://github.com/devttys0/binwalk/wiki/Frequently-Asked-Questions#how-do-i-plot-entropy-graphs-without-an-x-server). Unfortunately, the pyqtgraph graphing library relies on QT functionality that requires an X server, even if just generating an output file and not displaying it (there is a StackOverflow discussion on the matter [here](https://stackoverflow.com/questions/23739129/exporting-a-plot-in-gui-less-pyqtgraph)).

The FAQ describes how to use X virtual frame buffers to satisfy this X server requirement on GUI-less systems.

**Comment by fake-name** [comment]
Whoops, I missed that in the FAQ. Derp.

FWIW, it's not that I don't know how to use a XVFB to work around the issue, it's that installing any windowing environment makes a huge mess and installs a giant number of additional packages, and I'm running headless to (among other reasons) keep the linux install small.

Have you considered another graphing backend? If you're just throwing up simple static graphs (rather then dynamic stuff), matplotlib is quite nice, and doesn't have the attachment to QT that pyqtgraph does.

**Comment by devttys0** [comment]
For this, and various other reasons, the latest commits of  binwalk have switched to using matplotlib instead of pyqtgraph. This should alleviate any X server issues!

**Comment by fake-name** [comment]
Fancypants! Matplotlib is really nice too.
